#!/bin/bash

apt-get install -y openjdk-8-jdk

apt-get install -y  git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-mul tilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache libgl1-mesa-dev libxml2-utils xsltproc unzip

apt-get install -y libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa-dev g++-multilib 
apt-get install -y git flex bison gperf build-essential libncurses5-dev:i386 
apt-get install -y tofrodos python-markdown libxml2-utils xsltproc zlib1g-dev:i386 
apt-get install -y dpkg-dev libsdl1.2-dev libesd0-dev
apt-get install -y git-core gnupg flex bison gperf build-essential  
apt-get install -y zip curl zlib1g-dev gcc-multilib g++-multilib 
apt-get install -y libc6-dev-i386 
apt-get install -y lib32ncurses5-dev x11proto-core-dev libx11-dev 
apt-get install -y libgl1-mesa-dev libxml2-utils xsltproc unzip m4
apt-get install -y lib32z-dev ccache
